# Generated by Django 4.2.5 on 2023-09-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Adet')),
            ],
        ),
    ]
